<nav id="nav">
                            <ul>
                                <li><a href="index.html">Home</a></li>
                                <li><a href="history.html">History</a></li>
                                <li><a href="beers.html">Beers</a></li>
                                <li>
                                    <a href="/kzarrehparvar">Homeworks <span class="caret"></span></a>
                                    <div>
                                        <ul>
                                            <li><a href="http://students.thenet.ca/kzarrehparvar/">Homework 1</a></li>
                                            <li><a href="http://students.thenet.ca/kzarrehparvar/homework2">Homework 2</a></li>
                                            <li><a href="#">Homework 3</a></li>
                                        </ul>

                                    </div>
                                </li>
                                <li><a href="contact.html">Contact</a></li>

                            </ul>

                        </nav>